# Generated by Django 3.1.7 on 2021-03-25 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='TIME'),
        ),
    ]
