# Generated by Django 3.1.7 on 2021-03-25 21:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0003_auto_20210325_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='date'),
        ),
    ]
